"""The migrations must describe the same schema as the models.

Autogenerated migrations drift the moment someone edits a model and forgets to
revise. This test applies the whole migration history to an empty database and
asks Alembic whether anything still differs from ``Base.metadata``; anything but
"nothing" is a schema that production would not have.
"""

from __future__ import annotations

import asyncio
from pathlib import Path

import pytest
from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.config import Config
from alembic.migration import MigrationContext
from sqlalchemy import Connection, text

from infrastructure.database.engine import create_database_engine
from infrastructure.database.models import Base

pytestmark = pytest.mark.integration

PROJECT_ROOT = Path(__file__).resolve().parents[2]


def _alembic_config(url: str) -> Config:
    config = Config(str(PROJECT_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(PROJECT_ROOT / "alembic"))
    # Passed through the config rather than the environment: the test must not
    # depend on, nor leak into, the DATABASE_URL of whoever is running it.
    config.set_main_option("sqlalchemy.url", url)
    return config


def _diff(connection: Connection) -> list[object]:
    context = MigrationContext.configure(connection, opts={"compare_type": True})
    return list(compare_metadata(context, Base.metadata))


async def test_the_initial_migration_produces_the_models_schema(postgres_url: str) -> None:
    engine = create_database_engine(postgres_url, pool_size=1, max_overflow=0)
    async with engine.begin() as connection:
        await connection.run_sync(Base.metadata.drop_all)
        await connection.execute(text("DROP TABLE IF EXISTS alembic_version"))
    await engine.dispose()

    config = _alembic_config(postgres_url)
    # Alembic's command layer is synchronous and its ``env.py`` calls
    # ``asyncio.run``; a worker thread gives it the loop-free context it needs.
    await asyncio.to_thread(command.upgrade, config, "head")

    engine = create_database_engine(postgres_url, pool_size=1, max_overflow=0)
    try:
        async with engine.connect() as connection:
            differences = await connection.run_sync(_diff)
    finally:
        await engine.dispose()

    assert differences == [], f"models and migrations disagree: {differences}"


async def test_the_migration_history_is_reversible(postgres_url: str) -> None:
    """A migration nobody can undo is a migration nobody dares deploy."""
    config = _alembic_config(postgres_url)
    await asyncio.to_thread(command.upgrade, config, "head")
    await asyncio.to_thread(command.downgrade, config, "base")

    engine = create_database_engine(postgres_url, pool_size=1, max_overflow=0)
    try:
        async with engine.connect() as connection:
            remaining = await connection.run_sync(
                lambda sync_connection: sorted(
                    row[0]
                    for row in sync_connection.execute(
                        text("SELECT tablename FROM pg_tables WHERE schemaname = current_schema()")
                    )
                )
            )
    finally:
        await engine.dispose()

    assert remaining == ["alembic_version"]
    # Leave the database migrated so the ordering of tests never matters.
    await asyncio.to_thread(command.upgrade, config, "head")
